name: BE For CD

on: 
  push:
    branches: ["dev"]

jobs:
  build:
    environment: test
    runs-on: ubuntu-latest
    env:
      host port: ${{secrets.MYSQL_DB_PORT}}
      container port: ${{secrets.MYSQL_DB_PORT}}
      database user: ${{secrets.MYSQL_DB_NAME}}
      mysql password: ${{secrets.MYSQL_DB_PASSWORD}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v4

      - name: Set Up Gradle
        uses: gradle/actions/setup-gradle@v3
        with: 
          cache-write-only: true

      - name: Grant Execute Permission For Gradlew
        run: chmod +x gradlew

      - name: Build With Gradle
        run: ./gradlew bootJar

      - name: Login To Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_HUB_ID}}
          password: ${{secrets.DOCKER_HUB_TOKEN}}
          
      - name: Build And Push Image

deploy:
  
          
      
